# Generated by Django 3.2.6 on 2021-09-03 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='provider',
            new_name='providers',
        ),
        migrations.AlterField(
            model_name='provider',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Название магазина'),
        ),
    ]
