# Generated by Django 3.2.6 on 2021-09-04 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0002_auto_20210903_0835'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='providers',
            new_name='providers_info',
        ),
    ]
