# Generated by Django 3.2.6 on 2021-09-06 13:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order_app', '0005_alter_price_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='provider',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('WORKING', 'Заказы принимаются'), ('NOT WORKING', 'Заказы не принимаются')], max_length=15, verbose_name='Статус'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('WORKING', 'Заказы принимаются'), ('NOT WORKING', 'Заказы не принимаются')], max_length=15, verbose_name='Статус')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
            },
        ),
        migrations.AlterField(
            model_name='price',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price', to='order_app.userprofile'),
        ),
        migrations.AlterField(
            model_name='product',
            name='providers_info',
            field=models.ManyToManyField(related_name='products', through='order_app.Price', to='order_app.UserProfile'),
        ),
        migrations.DeleteModel(
            name='Provider',
        ),
    ]
