# Generated by Django 3.2.6 on 2021-09-06 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0007_auto_20210906_1540'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.RemoveField(
            model_name='order',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
        migrations.RemoveField(
            model_name='order',
            name='updated_at',
        ),
    ]
