# Generated by Django 3.2.6 on 2021-09-06 21:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order_app', '0008_auto_20210906_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='provider',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='position', to='auth.user'),
            preserve_default=False,
        ),
    ]
