# Generated by Django 3.2.7 on 2021-09-20 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0010_rename_products_order_products_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.TextField(default='NEW', verbose_name=[('NEW', 'Новый'), ('IN_PROGRESS', 'Выполняется'), ('DONE', 'Готов'), ('CANCELLED', 'Отменён')]),
        ),
    ]
