# Generated by Django 3.2.7 on 2021-09-23 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0012_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, default=224, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='order_app.category', verbose_name='Категория'),
        ),
    ]
