# Generated by Django 3.2.7 on 2021-09-23 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0014_alter_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='providers',
        ),
    ]
